// Fix kit: a corrected robots.txt (pro-AI defaults, your training choices kept),
// an llms.txt draft (honestly labeled), and IndexNow setup. Deterministic.

import { CRAWLERS, FAKE_TOKENS, ALIAS_SETS } from "./crawlers";
import { parseRobots, evaluateRobots } from "./robots";
import { probeAs, CONTROL_UA } from "./probe";

export interface FixKit {
  url: string;
  robotsTxt: {
    current: string | null;
    recommended: string;
    changes: { action: "unblock" | "keep-block" | "add-alias" | "remove-fake" | "add-sitemap"; detail: string }[];
  };
  llmsTxt: {
    label: string;
    draft: string;
  };
  indexNow: {
    label: string;
    key: string;
    steps: string[];
  };
}

export async function buildFixKit(rawUrl: string): Promise<FixKit> {
  const url = new URL(rawUrl);
  const pageRes = await probeAs(url.href, CONTROL_UA);
  const origin = new URL(pageRes.finalUrl || url.href).origin;
  const robotsRes = await probeAs(`${origin}/robots.txt`, CONTROL_UA);
  const hasRobots = robotsRes.ok && !!robotsRes.body && !/<html[\s>]/i.test(robotsRes.body.slice(0, 200));
  const robots = hasRobots ? parseRobots(robotsRes.body) : { groups: [], sitemaps: [], mentionedAgents: [] };
  const mentioned = robots.mentionedAgents.map((a) => a.toLowerCase());

  const changes: FixKit["robotsTxt"]["changes"] = [];
  const lines: string[] = [
    "# robots.txt — generated by amivisible",
    "# Citation-path AI bots allowed (they get you cited in AI answers);",
    "# your existing blocks on training-only bots are preserved.",
    "",
    "User-agent: *",
    "Allow: /",
  ];

  for (const c of CRAWLERS) {
    const verdict = evaluateRobots(robots, c.tokens[0], "/").verdict;
    if (c.trainingOnly) {
      if (verdict === "block") {
        for (const token of c.tokens) {
          lines.push("", `User-agent: ${token}`, "Disallow: /");
          if (!mentioned.includes(token.toLowerCase()) && c.tokens.length > 1) {
            changes.push({ action: "add-alias", detail: `${token} added — same crawler lineage as ${c.tokens[0]}, your block only covered part of it` });
          }
        }
        changes.push({ action: "keep-block", detail: `${c.name} stays blocked (training-only — blocking it costs you no citations)` });
      }
    } else if (verdict === "block") {
      lines.push("", `User-agent: ${c.tokens[0]}`, "Allow: /");
      changes.push({ action: "unblock", detail: `${c.name} unblocked — it powers ${c.operator} citations; blocking it removed you from AI answers without protecting anything from training` });
    }
  }

  const fakes = FAKE_TOKENS.filter((t) => mentioned.includes(t.toLowerCase()));
  for (const fake of fakes) {
    changes.push({ action: "remove-fake", detail: `${fake} stanza dropped — no vendor has ever documented this bot; the line blocked nothing` });
  }

  // sitemap: keep declared ones, else probe /sitemap.xml
  let sitemaps = robots.sitemaps;
  if (sitemaps.length === 0) {
    const sm = await probeAs(`${origin}/sitemap.xml`, CONTROL_UA);
    if (sm.ok && /<(urlset|sitemapindex)[\s>]/i.test(sm.body.slice(0, 2000))) {
      sitemaps = [`${origin}/sitemap.xml`];
      changes.push({ action: "add-sitemap", detail: "sitemap.xml exists but was not declared in robots.txt — declared it" });
    }
  }
  for (const sm of sitemaps) lines.push("", `Sitemap: ${sm}`);

  // llms.txt draft from page metadata + sitemap sample
  const title = pageRes.body.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.trim() ?? url.hostname;
  const description = pageRes.body.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']+)["']/i)?.[1]
    ?? pageRes.body.match(/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']description["']/i)?.[1] ?? "";
  const sampleUrls: string[] = [];
  if (sitemaps.length > 0) {
    const sm = await probeAs(sitemaps[0], CONTROL_UA);
    if (sm.ok) {
      for (const m of sm.body.matchAll(/<loc>\s*([^<\s]+)\s*<\/loc>/g)) {
        try {
          const u = new URL(m[1]);
          if (u.origin === origin) sampleUrls.push(u.href);
        } catch { /* skip malformed */ }
        if (sampleUrls.length >= 25) break;
      }
    }
  }
  const llmsDraft = [
    `# ${title}`,
    "",
    ...(description ? [`> ${description}`, ""] : []),
    "## Pages",
    "",
    ...(sampleUrls.length > 0 ? sampleUrls.map((u) => `- [${new URL(u).pathname}](${u})`) : [`- [/](${origin}/)`]),
  ].join("\n");

  const inKey = crypto.randomUUID().replace(/-/g, "");
  return {
    url: url.href,
    robotsTxt: { current: hasRobots ? robotsRes.body : null, recommended: lines.join("\n") + "\n", changes },
    llmsTxt: {
      label: "SPECULATIVE — no AI engine is documented to consume llms.txt (Ahrefs, N≈5k domains: zero attributable citations). Publish it if you like the convention; it will not move citations.",
      draft: llmsDraft,
    },
    indexNow: {
      label: "PROVEN for Bing only (which also grounds Copilot and part of ChatGPT Search). Google does not consume IndexNow.",
      key: inKey,
      steps: [
        `Host the key: put the text "${inKey}" at ${origin}/${inKey}.txt`,
        `On publish/update, POST your changed URLs to https://api.indexnow.org/indexnow with key=${inKey}`,
        "That's it — Bing (and Yandex/Naver/Seznam) pick up changes without waiting for a crawl.",
      ],
    },
  };
}
